<a href="https://colab.research.google.com/github/noamarko/TensorFlow/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [211]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.3.0


In [212]:
dim = 2  # Input dim
out_dim = 1
num_hidden = 4
Temp = 0.001  # for sigmoid
@tf.function
def Linear_model2(x, w, b):
  return tf.matmul(tf.cast(x, tf.float32), w) + b

In [213]:
@tf.function
def BTU_layer(x, w, b):    
  z1 = Linear_model2(x, w, b)  # [4, 2] X [dim, num_hidden] results in a vector [4, num_hidden] of z's. 
  # # Theoretically [1, num_hidden] for every input pair, which is the output of the hidden layer (before sigmoid).
  return tf.sigmoid(z1/Temp)  # Element wise

In [214]:
def Loss(x, w, b, n):

  squared_deltas = tf.square(Linear_model2(x, w, b) - 0)
  return tf.math.divide(tf.reduce_sum(squared_deltas), n, name = "MSE")

In [215]:
def Hw1(n,k,bypass):
  x = [[0, 0], [0, 1], [1, 0], [1, 1]]
  
  if k == 4:   
        w1 = [[-1,-1,1,1],[-1,1,-1,1]]
        b1 = [0.5, -0.5, -0.5, -1.5]
        w2 = [[-1],[1],[1],[-1]]
        b2 = 0.5
  else:
    if k == 2:
        w1 = [[1,-1],[-1,1]]
        b1 = [-0.5, -0.5]
        w2 = [[2],[2]]
        b2 = -0.5
    else:
        w1 = [[1],[1]]
        b1 = [-1.5]
        w2 = [[-2]]
        b2 = -0.5

  Hidden_Neurons(x, w1, b1, w2, b2, bypass, k)

In [216]:
def Hidden_Neurons(x_train, w1, b1, w2, b2, bypass, k):
  w1 = tf.Variable(w1, dtype=tf.float32, name="weights1") #creating the weights variable
  b1 = tf.Variable(b1, dtype=tf.float32, name="Biases1") #creating the biase variable
  tf.print("w1: ", w1)
  tf.print("b1: ", b1)
  hlayer = BTU_layer(x_train, w1, b1) #calculating the hidden layer (between w1 and w2)
  tf.print("hidden layer: ", hlayer)
  w2 = tf.Variable(w2, dtype=tf.float32, name="weights2") #creating the second weights variable
  tf.print("w2: ", w2)
  if bypass == '1':
    w_concat = Create_Weight_Concat(w2, k)
    print("w_concat: ", w_concat)
    b_concat = tf.Variable(b2, dtype=tf.float32, name="Biases1")
    print("b_concat: ", b_concat)
    hlayer_concat = tf.concat([hlayer, x_train], axis=1)
    print("hlayer_concat: ", hlayer_concat)
    out_concat = BTU_layer(hlayer_concat, w_concat, b_concat)
    tf.print("out_concat: ", out_concat)
    mse = Loss(hlayer_concat,w_concat,b_concat,4)
    tf.print("MSE:   ",mse)
  else:
    b2 = tf.Variable(b2, dtype=tf.float32, name="biase2") #creating the second biase  
    out = BTU_layer(hlayer, w2, b2) #calculating the final output 
    tf.print("output:    ", out)
    mse = Loss(hlayer,w2,b2,4)
    tf.print("MSE:   ",mse)

In [217]:
def Create_Weight_Concat(w2, k):
  if k == 4:
    w_concat = tf.Variable([[-1], [1]], dtype=tf.float32, name="weights2")
    return tf.concat([w2,w_concat], axis=0)
  else:
    if k == 2:
      w_concat = tf.Variable([[1], [-1]], dtype=tf.float32, name="weights2")
      return tf.concat([w2,w_concat], axis=0)
    else:
      w_concat = tf.Variable([[1], [1]], dtype=tf.float32, name="weights2")
      return tf.concat([w2,w_concat], axis=0)

In [221]:
n = 2
k = int(input("Number of hidden neuron: "))
bypass = input("Would you like to use a bypass? Press 1 for YES 0 for NO (NOTE: 1 hidden neuron has to use a bypass)")
Hw1(n, k, bypass)


Number of hidden neuron: 2
Would you like to use a bypass? Press 1 for YES 0 for NO (NOTE: 1 hidden neuron has to use a bypass)1
w1:  [[1 -1]
 [-1 1]]
b1:  [-0.5 -0.5]
hidden layer:  [[0 0]
 [0 1]
 [1 0]
 [0 0]]
w2:  [[2]
 [2]]
w_concat:  tf.Tensor(
[[ 2.]
 [ 2.]
 [ 1.]
 [-1.]], shape=(4, 1), dtype=float32)
b_concat:  <tf.Variable 'Biases1:0' shape=() dtype=float32, numpy=-0.5>
hlayer_concat:  tf.Tensor(
[[0. 0. 0. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 0. 1. 1.]], shape=(4, 4), dtype=float32)
out_concat:  [[0]
 [1]
 [1]
 [0]]
MSE:    1.75
